/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransaccionesRouteImport } from './routes/transacciones'
import { Route as PresupuestosRouteImport } from './routes/presupuestos'
import { Route as NuevaTransaccionRouteImport } from './routes/nuevaTransaccion'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'

const TransaccionesRoute = TransaccionesRouteImport.update({
  id: '/transacciones',
  path: '/transacciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosRoute = PresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaTransaccionRoute = NuevaTransaccionRouteImport.update({
  id: '/nuevaTransaccion',
  path: '/nuevaTransaccion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/nuevaTransaccion': typeof NuevaTransaccionRoute
  '/presupuestos': typeof PresupuestosRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/nuevaTransaccion': typeof NuevaTransaccionRoute
  '/presupuestos': typeof PresupuestosRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/nuevaTransaccion': typeof NuevaTransaccionRoute
  '/presupuestos': typeof PresupuestosRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/nuevaTransaccion'
    | '/presupuestos'
    | '/transacciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/nuevaTransaccion'
    | '/presupuestos'
    | '/transacciones'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/nuevaTransaccion'
    | '/presupuestos'
    | '/transacciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  NuevaTransaccionRoute: typeof NuevaTransaccionRoute
  PresupuestosRoute: typeof PresupuestosRoute
  TransaccionesRoute: typeof TransaccionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacciones': {
      id: '/transacciones'
      path: '/transacciones'
      fullPath: '/transacciones'
      preLoaderRoute: typeof TransaccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos': {
      id: '/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof PresupuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevaTransaccion': {
      id: '/nuevaTransaccion'
      path: '/nuevaTransaccion'
      fullPath: '/nuevaTransaccion'
      preLoaderRoute: typeof NuevaTransaccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  NuevaTransaccionRoute: NuevaTransaccionRoute,
  PresupuestosRoute: PresupuestosRoute,
  TransaccionesRoute: TransaccionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
